# Generated by Django 6.0.4 on 2026-04-22 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedcapProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source_project_id', models.CharField(max_length=50)),
                ('source_url', models.URLField(help_text='e.g https://site-a.edu/redcap/api/')),
                ('source_token', models.CharField(max_length=255)),
                ('target_project_id', models.CharField(max_length=50)),
                ('target_url', models.URLField(help_text='e.g https://central-hub.edu/redcap/api/')),
                ('target_token', models.CharField(max_length=255)),
                ('last_sync_timestamp', models.DateTimeField(blank=True, null=True)),
                ('overlap_minutes', models.PositiveIntegerField(default=1)),
                ('chunk_size', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('SU', 'Success'), ('FA', 'Failed')], default='PE', max_length=2)),
                ('records_synced', models.PositiveIntegerField(default=0)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projects.redcapproject')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
