# Generated by Django 6.0.4 on 2026-04-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redcapproject',
            name='record_identifier_field',
            field=models.CharField(default='record_id', max_length=100),
        ),
        migrations.AddField(
            model_name='synclog',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
