# Generated by Django 6.0.4 on 2026-04-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_redcapproject_record_identifier_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='error_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='records_expected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='records_failed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
