# Generated by Django 6.0.4 on 2026-04-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_syncrecordlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='completed_batches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='total_batches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='syncrecordlog',
            index=models.Index(fields=['sync_log', 'status'], name='projects_sy_sync_lo_5ea54c_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrecordlog',
            index=models.Index(fields=['record_id'], name='projects_sy_record__a9db7d_idx'),
        ),
    ]
