# Generated by Django 6.0.4 on 2026-04-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_synclog_completed_batches_synclog_total_batches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('RU', 'Running'), ('SU', 'Success'), ('FA', 'Failed')], default='PE', max_length=2),
        ),
    ]
